# Generated by Django 4.2.7 on 2023-11-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_item_dairy_item_itemid_item_key_item_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addons',
            fields=[
                ('addonid', models.IntegerField(primary_key=True, serialize=False)),
                ('addonname', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('dairy', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'addons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('key', models.IntegerField(primary_key=True, serialize=False)),
                ('itemid', models.IntegerField(blank=True, null=True)),
                ('itemname', models.TextField(blank=True, null=True)),
                ('stockid', models.IntegerField(blank=True, null=True)),
                ('dairy', models.BooleanField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Merch',
            fields=[
                ('merchid', models.IntegerField(primary_key=True, serialize=False)),
                ('merchname', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'merch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderid', models.IntegerField(primary_key=True, serialize=False)),
                ('itemid', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('customername', models.TextField(blank=True, null=True)),
                ('takeout', models.BooleanField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stockid', models.IntegerField(primary_key=True, serialize=False)),
                ('stockname', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('unit', models.TextField(blank=True, null=True)),
                ('use', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
            ],
            options={
                'db_table': 'stock',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
